services:
  nginx:
    build: ./nginx
    networks:
      - webnet
    depends_on:
      - uk1
      - us1
      - us2
      - global1
      - backup
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    ports:
      - "8086:80"
    restart: always

  uk1:
    image: nginx:latest
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    volumes:
      - ./templates/uk/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
    restart: always

  us1:
    image: nginx:latest
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    volumes:
      - ./templates/us/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"
    restart: always

  us2:
    image: nginx:latest
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    volumes:
      - ./templates/us/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8083:80"
    restart: always

  global1:
    image: nginx:latest
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    volumes:
      - ./templates/rest/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8084:80"
    restart: always

  backup:
    image: nginx:latest
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 3
    volumes:
      - ./templates/backup/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8085:80"
    restart: always

networks:
  webnet:
    driver: bridge
